### ISSUE TITLE
Spirit manifest photos objects have no earth_date

### ISSUE THREAD

**Issue by Oshuma** [chrisccerami/mars-photo-api#104]
Curiosity and Opportunity manifests both have an `earth_date` attribute for their photos objects. See comparison snippets below.

```json
// Curiosity manifest
    "photos": [
      {
        "sol": 0,
        "earth_date": "2012-08-06",
        "total_photos": 3702,
        "cameras": [
          "CHEMCAM",
          "FHAZ",
          "MARDI",
          "RHAZ"
        ]
      }
```

```json
// Spirit manifest
    "photos": [
      {
        "sol": 1,
        "total_photos": 77,
        "cameras": [
          "ENTRY",
          "FHAZ",
          "NAVCAM",
          "PANCAM",
          "RHAZ"
        ]
      }
```

**Comment by chrisccerami** [comment]
Thanks for reporting this. What happened is there was previously a bug causing the earth_date to not appear. While that had been fixed a while ago, the cached manifest was never updated for Spirit since the rover has been inactive for so long, and the system saw no need to update the cache. I deleted the old cached manifest and generated a fresh one, and it looks like the earth_date field is back now.
