### ISSUE TITLE
NASA URL changed for API

### ISSUE THREAD

**Issue by PaulSolt** [chrisccerami/mars-photo-api#92]
The url in the description doesn’t work, and previous links fail because the NASA website now appears to be a web app without links to content on page.

**Comment by MDutro** [comment]
I'm having the same issue. Request either 403/4 or return an empty array.

**Comment by rbenza** [comment]
The V1 still works: https://api.nasa.gov/mars-photos/api/v1/rovers/curiosity/photos?sol=1000&camera=fhaz&api_key=DEMO_KEY

But it's stuck on sol 2540, like previously [reported](https://github.com/chrisccerami/mars-photo-api/issues/88). @chrisccerami maybe you can shed some light on this? My Android app isn't getting new photo's since sept 2019.

**Comment by chrisccerami** [comment]
Thanks. That link is only meant to be for the official NASA documentation/description of the API and not for querying. I've updated the URL to one that works, although the page has been reformatting so that linking directly to the relevant location for this API is tricky.
